// Generated by RScheme compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>

// Forward declarations
typedef struct Environment Environment;

// Scheme object types
typedef enum {
    SCHEME_NIL, SCHEME_BOOLEAN, SCHEME_NUMBER,
    SCHEME_SYMBOL, SCHEME_STRING, SCHEME_PAIR,
    SCHEME_PROCEDURE, SCHEME_PRIMITIVE
} SchemeType;

typedef struct SchemeObject {
    SchemeType type;
    union {
        bool boolean_value;
        double number_value;
        char* string_value;
        char* symbol_name;
        struct { struct SchemeObject* car; struct SchemeObject* cdr; } pair;
        struct {
            struct SchemeObject* parameters;  // List of parameter symbols (for interpreted)
            struct SchemeObject* body;        // List of expressions (for interpreted)
            Environment* closure;             // Captured environment (for interpreted)
            struct SchemeObject* (*func)(struct SchemeObject**, int); // Function pointer (for compiled)
            int arity;                        // Number of parameters
            char* name;                       // Function name (for debugging)
        } procedure;
    } value;
} SchemeObject;

// Runtime functions
SchemeObject* scheme_nil;
SchemeObject* scheme_true;
SchemeObject* scheme_false;

// Function declarations
void scheme_display(SchemeObject* obj);
void scheme_display_list(SchemeObject* obj);
SchemeObject* lookup_variable(const char* name);
void define_variable(const char* name, SchemeObject* value);

// Global variables (simple implementation)
#define MAX_VARS 100
char* var_names[MAX_VARS];
SchemeObject* var_values[MAX_VARS];
int var_count = 0;

// Runtime functions
SchemeObject* scheme_nil;
SchemeObject* scheme_true;
SchemeObject* scheme_false;

SchemeObject* make_number(double value) {
    SchemeObject* obj = malloc(sizeof(SchemeObject));
    obj->type = SCHEME_NUMBER;
    obj->value.number_value = value;
    return obj;
}

SchemeObject* make_boolean(bool value) {
    return value ? scheme_true : scheme_false;
}

SchemeObject* make_string(const char* value) {
    SchemeObject* obj = malloc(sizeof(SchemeObject));
    obj->type = SCHEME_STRING;
    obj->value.string_value = malloc(strlen(value) + 1);
    strcpy(obj->value.string_value, value);
    return obj;
}

SchemeObject* make_symbol(const char* name) {
    SchemeObject* obj = malloc(sizeof(SchemeObject));
    obj->type = SCHEME_SYMBOL;
    obj->value.symbol_name = malloc(strlen(name) + 1);
    strcpy(obj->value.symbol_name, name);
    return obj;
}

SchemeObject* make_pair(SchemeObject* car, SchemeObject* cdr) {
    SchemeObject* obj = malloc(sizeof(SchemeObject));
    obj->type = SCHEME_PAIR;
    obj->value.pair.car = car;
    obj->value.pair.cdr = cdr;
    return obj;
}

bool is_true(SchemeObject* obj) {
    return obj != scheme_false;
}

bool is_number(SchemeObject* obj) {
    return obj && obj->type == SCHEME_NUMBER;
}

bool is_boolean(SchemeObject* obj) {
    return obj && obj->type == SCHEME_BOOLEAN;
}

bool is_string(SchemeObject* obj) {
    return obj && obj->type == SCHEME_STRING;
}

bool is_pair(SchemeObject* obj) {
    return obj && obj->type == SCHEME_PAIR;
}

bool is_nil(SchemeObject* obj) {
    return obj == scheme_nil;
}

bool is_procedure(SchemeObject* obj) {
    return obj && obj->type == SCHEME_PROCEDURE;
}

bool is_symbol(SchemeObject* obj) {
    return obj && obj->type == SCHEME_SYMBOL;
}

SchemeObject* call_procedure(SchemeObject* proc, SchemeObject** args, int argc) {
    if (!proc || !is_procedure(proc)) {
        return scheme_nil;
    }
    
    // Check if it's a compiled procedure (has func pointer)
    if (proc->value.procedure.func) {
        return proc->value.procedure.func(args, argc);
    }
    
    // For interpreted procedures, we can't handle them in compiled code
    // This would require a full interpreter runtime
    return scheme_nil;
}

SchemeObject* car(SchemeObject* obj) {
    if (is_pair(obj)) return obj->value.pair.car;
    return scheme_nil;
}

SchemeObject* cdr(SchemeObject* obj) {
    if (is_pair(obj)) return obj->value.pair.cdr;
    return scheme_nil;
}

SchemeObject* scheme_add(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_number(a->value.number_value + b->value.number_value);
    }
    return scheme_nil;
}

SchemeObject* scheme_subtract(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_number(a->value.number_value - b->value.number_value);
    }
    return scheme_nil;
}

SchemeObject* scheme_multiply(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_number(a->value.number_value * b->value.number_value);
    }
    return scheme_nil;
}

SchemeObject* scheme_divide(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b) && b->value.number_value != 0) {
        return make_number(a->value.number_value / b->value.number_value);
    }
    return scheme_nil;
}

SchemeObject* scheme_equal(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_boolean(a->value.number_value == b->value.number_value);
    }
    return make_boolean(false);
}

SchemeObject* scheme_less_than(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_boolean(a->value.number_value < b->value.number_value);
    }
    return make_boolean(false);
}

SchemeObject* scheme_greater_than(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_boolean(a->value.number_value > b->value.number_value);
    }
    return make_boolean(false);
}

void scheme_display(SchemeObject* obj) {
    if (is_number(obj)) {
        printf("%g", obj->value.number_value);
    } else if (is_boolean(obj)) {
        printf("%s", obj->value.boolean_value ? "#t" : "#f");
    } else if (is_string(obj)) {
        printf("%s", obj->value.string_value);
    } else if (obj && obj->type == SCHEME_SYMBOL) {
        printf("%s", obj->value.symbol_name);
    } else if (is_pair(obj)) {
        scheme_display_list(obj);
    } else if (is_nil(obj)) {
        printf("()");
    } else {
        printf("(...)");
    }
}

void scheme_display_list(SchemeObject* obj) {
    printf("(");
    while (is_pair(obj)) {
        scheme_display(obj->value.pair.car);
        obj = obj->value.pair.cdr;
        if (is_pair(obj)) {
            printf(" ");
        } else if (!is_nil(obj)) {
            printf(" . ");
            scheme_display(obj);
        }
    }
    printf(")");
}

void init_runtime() {
    scheme_nil = malloc(sizeof(SchemeObject));
    scheme_nil->type = SCHEME_NIL;
    
    scheme_true = malloc(sizeof(SchemeObject));
    scheme_true->type = SCHEME_BOOLEAN;
    scheme_true->value.boolean_value = true;
    
    scheme_false = malloc(sizeof(SchemeObject));
    scheme_false->type = SCHEME_BOOLEAN;
    scheme_false->value.boolean_value = false;
}

SchemeObject* scheme_less(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_boolean(a->value.number_value < b->value.number_value);
    }
    return scheme_false;
}

SchemeObject* scheme_greater(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_boolean(a->value.number_value > b->value.number_value);
    }
    return scheme_false;
}

SchemeObject* scheme_less_equal(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_boolean(a->value.number_value <= b->value.number_value);
    }
    return scheme_false;
}

SchemeObject* scheme_greater_equal(SchemeObject* a, SchemeObject* b) {
    if (is_number(a) && is_number(b)) {
        return make_boolean(a->value.number_value >= b->value.number_value);
    }
    return scheme_false;
}

SchemeObject* scheme_car(SchemeObject* pair) {
    if (is_pair(pair)) {
        return pair->value.pair.car;
    }
    return scheme_nil;
}

SchemeObject* scheme_cdr(SchemeObject* pair) {
    if (is_pair(pair)) {
        return pair->value.pair.cdr;
    }
    return scheme_nil;
}

SchemeObject* scheme_cons(SchemeObject* car, SchemeObject* cdr) {
    return make_pair(car, cdr);
}

SchemeObject* make_compiled_procedure(SchemeObject* (*func)(SchemeObject**, int), int arity, const char* name) {
    SchemeObject* obj = malloc(sizeof(SchemeObject));
    obj->type = SCHEME_PROCEDURE;
    obj->value.procedure.func = func;
    obj->value.procedure.arity = arity;
    obj->value.procedure.name = malloc(strlen(name) + 1);
    strcpy(obj->value.procedure.name, name);
    obj->value.procedure.parameters = NULL;
    obj->value.procedure.body = NULL;
    obj->value.procedure.closure = NULL;
    return obj;
}

SchemeObject* make_procedure(SchemeObject* params, SchemeObject* body, Environment* env) {
    SchemeObject* obj = malloc(sizeof(SchemeObject));
    obj->type = SCHEME_PROCEDURE;
    obj->value.procedure.parameters = params;
    obj->value.procedure.body = body;
    obj->value.procedure.closure = env;
    obj->value.procedure.func = NULL; // Interpreted procedure
    obj->value.procedure.arity = 0;
    obj->value.procedure.name = NULL;
    return obj;
}

SchemeObject* scheme_number_p(SchemeObject* obj) {
    return make_boolean(is_number(obj));
}

SchemeObject* scheme_boolean_p(SchemeObject* obj) {
    return make_boolean(obj && obj->type == SCHEME_BOOLEAN);
}

SchemeObject* scheme_string_p(SchemeObject* obj) {
    return make_boolean(obj && obj->type == SCHEME_STRING);
}

SchemeObject* scheme_symbol_p(SchemeObject* obj) {
    return make_boolean(obj && obj->type == SCHEME_SYMBOL);
}

SchemeObject* scheme_pair_p(SchemeObject* obj) {
    return make_boolean(is_pair(obj));
}

SchemeObject* scheme_null_p(SchemeObject* obj) {
    return make_boolean(is_nil(obj));
}

SchemeObject* scheme_procedure_p(SchemeObject* obj) {
    return make_boolean(obj && (obj->type == SCHEME_PROCEDURE || obj->type == SCHEME_PRIMITIVE));
}

SchemeObject* scheme_length(SchemeObject* obj) {
    int count = 0;
    while (is_pair(obj)) {
        count++;
        obj = obj->value.pair.cdr;
    }
    return make_number(count);
}

SchemeObject* scheme_string_length(SchemeObject* obj) {
    if (obj && obj->type == SCHEME_STRING) {
        return make_number(strlen(obj->value.string_value));
    }
    return scheme_nil;
}

SchemeObject* scheme_string_ref(SchemeObject* str, SchemeObject* index) {
    if (str && str->type == SCHEME_STRING && is_number(index)) {
        int idx = (int)index->value.number_value;
        int len = strlen(str->value.string_value);
        if (idx >= 0 && idx < len) {
            char result[2];
            result[0] = str->value.string_value[idx];
            result[1] = 0;
            return make_string(result);
        }
    }
    return scheme_nil;
}

SchemeObject* scheme_list_ref(SchemeObject* list, SchemeObject* index) {
    if (!is_number(index)) return scheme_nil;
    int idx = (int)index->value.number_value;
    if (idx < 0) return scheme_nil;
    SchemeObject* current = list;
    for (int i = 0; i < idx && is_pair(current); i++) {
        current = current->value.pair.cdr;
    }
    if (is_pair(current)) {
        return current->value.pair.car;
    }
    return scheme_nil;
}

SchemeObject* scheme_append(SchemeObject* list1, SchemeObject* list2) {
    if (is_nil(list1)) return list2;
    if (is_nil(list2)) return list1;
    if (!is_pair(list1)) return list2;
    // Create a new list by copying list1 and appending list2
    SchemeObject* result = scheme_nil;
    SchemeObject* tail = NULL;
    SchemeObject* current = list1;
    // Copy all elements from list1
    while (is_pair(current)) {
        SchemeObject* new_pair = make_pair(current->value.pair.car, scheme_nil);
        if (is_nil(result)) {
            result = new_pair;
            tail = new_pair;
        } else {
            tail->value.pair.cdr = new_pair;
            tail = new_pair;
        }
        current = current->value.pair.cdr;
    }
    // Append list2 to the end
    if (tail) {
        tail->value.pair.cdr = list2;
    } else {
        result = list2;
    }
    return result;
}

SchemeObject* scheme_reverse(SchemeObject* list) {
    SchemeObject* result = scheme_nil;
    SchemeObject* current = list;
    while (is_pair(current)) {
        result = make_pair(current->value.pair.car, result);
        current = current->value.pair.cdr;
    }
    return result;
}

int is_builtin_function(const char* name) {
    const char* builtins[] = {
        "+", "-", "*", "/", "=", "<", ">", "<=", ">=",
        "car", "cdr", "cons", "length", "list-ref", "append", "reverse",
        "display", "newline", "string-length", "string-ref",
        "number?", "boolean?", "string?", "symbol?", "pair?", "null?", "procedure?",
        NULL
    };
    for (int i = 0; builtins[i] != NULL; i++) {
        if (strcmp(name, builtins[i]) == 0) return 1;
    }
    return 0;
}

SchemeObject* lookup_variable(const char* name) {
    for (int i = 0; i < var_count; i++) {
        if (strcmp(var_names[i], name) == 0) {
            return var_values[i];
        }
    }
    // Check for built-in functions and return primitive objects
    if (is_builtin_function(name)) {
        SchemeObject* prim = malloc(sizeof(SchemeObject));
        prim->type = SCHEME_PRIMITIVE;
        return prim; // Return primitive for built-in functions
    }
    return make_symbol(name); // Return symbol if not found
}

void define_variable(const char* name, SchemeObject* value) {
    // Check if variable already exists
    for (int i = 0; i < var_count; i++) {
        if (strcmp(var_names[i], name) == 0) {
            var_values[i] = value;
            return;
        }
    }
    // Add new variable
    if (var_count < MAX_VARS) {
        var_names[var_count] = malloc(strlen(name) + 1);
        strcpy(var_names[var_count], name);
        var_values[var_count] = value;
        var_count++;
    }
}

// DEBUG: About to emit lambda functions
// DEBUG: Attempting to emit lambda functions
// Lambda function declarations
// DEBUG: Emitting lambda function 1: lambda_func_4
// Generated lambda function
SchemeObject* lambda_func_4(SchemeObject** args, int argc) {
    SchemeObject* result;
    // Bind parameters locally
    SchemeObject* local_x = (argc > 0) ? args[0] : scheme_nil;
    // Function body
    {
        SchemeObject* func = lookup_variable("square");
        SchemeObject* args_array[1];
        {
            SchemeObject* arg_temp;
        {
            SchemeObject* temp1;
            SchemeObject* temp2;
        temp1 = local_x;
        temp2 = make_number(1);
            arg_temp = scheme_add(temp1, temp2);
        }
            args_array[0] = arg_temp;
        }
        if (func && is_procedure(func)) {
            result = call_procedure(func, args_array, 1);
        } else {
            result = scheme_nil;
        }
    }
    return result;
}

// DEBUG: Emitting lambda function 2: lambda_func_3
// Generated lambda function
SchemeObject* lambda_func_3(SchemeObject** args, int argc) {
    SchemeObject* result;
    // Bind parameters locally
    SchemeObject* local_n = (argc > 0) ? args[0] : scheme_nil;
    // Function body
    {
        SchemeObject* condition_result;
        {
            SchemeObject* temp1;
            SchemeObject* temp2;
        temp1 = local_n;
        temp2 = make_number(0);
            condition_result = scheme_equal(temp1, temp2);
        }
        if (is_true(condition_result)) {
        result = make_number(1);
        } else {
        {
            SchemeObject* temp1;
            SchemeObject* temp2;
        temp1 = local_n;
        {
            SchemeObject* func = lookup_variable("factorial");
            SchemeObject* args_array[1];
            {
                SchemeObject* arg_temp;
        {
            SchemeObject* temp1;
            SchemeObject* temp2;
        temp1 = local_n;
        temp2 = make_number(1);
            arg_temp = scheme_subtract(temp1, temp2);
        }
                args_array[0] = arg_temp;
            }
            if (func && is_procedure(func)) {
                temp2 = call_procedure(func, args_array, 1);
            } else {
                temp2 = scheme_nil;
            }
        }
            result = scheme_multiply(temp1, temp2);
        }
        }
    }
    return result;
}

// DEBUG: Emitting lambda function 3: lambda_func_2
// Generated lambda function
SchemeObject* lambda_func_2(SchemeObject** args, int argc) {
    SchemeObject* result;
    // Function body
    result = make_number(3.14159);
    return result;
}

// DEBUG: Emitting lambda function 4: lambda_func_1
// Generated lambda function
SchemeObject* lambda_func_1(SchemeObject** args, int argc) {
    SchemeObject* result;
    // Bind parameters locally
    SchemeObject* local_x = (argc > 0) ? args[0] : scheme_nil;
    SchemeObject* local_y = (argc > 1) ? args[1] : scheme_nil;
    // Function body
    {
        SchemeObject* temp1;
        SchemeObject* temp2;
        temp1 = local_x;
        temp2 = local_y;
        result = scheme_add(temp1, temp2);
    }
    return result;
}

// DEBUG: Emitting lambda function 5: lambda_func_0
// Generated lambda function
SchemeObject* lambda_func_0(SchemeObject** args, int argc) {
    SchemeObject* result;
    // Bind parameters locally
    SchemeObject* local_x = (argc > 0) ? args[0] : scheme_nil;
    // Function body
    {
        SchemeObject* temp1;
        SchemeObject* temp2;
        temp1 = local_x;
        temp2 = local_x;
        result = scheme_multiply(temp1, temp2);
    }
    return result;
}

// DEBUG: Emitted 5 lambda functions

// DEBUG: Finished emitting lambda functions
int main() {
    init_runtime();
    SchemeObject* result;

// Display
SchemeObject* temp_0;
result = make_string("=== R5RS Scheme Compliance Test Suite ===");
temp_0 = result;
scheme_display(temp_0);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_1;
result = make_string("1. Testing Basic Data Types");
temp_1 = result;
scheme_display(temp_1);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_2;
result = make_string("Numbers: ");
temp_2 = result;
scheme_display(temp_2);
result = scheme_nil;

// Display
SchemeObject* temp_3;
result = make_number(42);
temp_3 = result;
scheme_display(temp_3);
result = scheme_nil;

// Display
SchemeObject* temp_4;
result = make_string(" ");
temp_4 = result;
scheme_display(temp_4);
result = scheme_nil;

// Display
SchemeObject* temp_5;
result = make_number(-17);
temp_5 = result;
scheme_display(temp_5);
result = scheme_nil;

// Display
SchemeObject* temp_6;
result = make_string(" ");
temp_6 = result;
scheme_display(temp_6);
result = scheme_nil;

// Display
SchemeObject* temp_7;
result = make_number(3.14);
temp_7 = result;
scheme_display(temp_7);
result = scheme_nil;

// Display
SchemeObject* temp_8;
result = make_string(" ");
temp_8 = result;
scheme_display(temp_8);
result = scheme_nil;

// Display
SchemeObject* temp_9;
result = make_number(0);
temp_9 = result;
scheme_display(temp_9);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_10;
result = make_string("Booleans: ");
temp_10 = result;
scheme_display(temp_10);
result = scheme_nil;

// Display
SchemeObject* temp_11;
result = make_boolean(true);
temp_11 = result;
scheme_display(temp_11);
result = scheme_nil;

// Display
SchemeObject* temp_12;
result = make_string(" ");
temp_12 = result;
scheme_display(temp_12);
result = scheme_nil;

// Display
SchemeObject* temp_13;
result = make_boolean(false);
temp_13 = result;
scheme_display(temp_13);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_14;
result = make_string("Strings: ");
temp_14 = result;
scheme_display(temp_14);
result = scheme_nil;

// Display
SchemeObject* temp_15;
result = make_string("hello");
temp_15 = result;
scheme_display(temp_15);
result = scheme_nil;

// Display
SchemeObject* temp_16;
result = make_string(" ");
temp_16 = result;
scheme_display(temp_16);
result = scheme_nil;

// Display
SchemeObject* temp_17;
result = make_string("world");
temp_17 = result;
scheme_display(temp_17);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_18;
result = make_string("Symbols: ");
temp_18 = result;
scheme_display(temp_18);
result = scheme_nil;

// Display
SchemeObject* temp_19;
// Quote
result = make_symbol("hello");
temp_19 = result;
scheme_display(temp_19);
result = scheme_nil;

// Display
SchemeObject* temp_20;
result = make_string(" ");
temp_20 = result;
scheme_display(temp_20);
result = scheme_nil;

// Display
SchemeObject* temp_21;
// Quote
result = make_symbol("x");
temp_21 = result;
scheme_display(temp_21);
result = scheme_nil;

// Display
SchemeObject* temp_22;
result = make_string(" ");
temp_22 = result;
scheme_display(temp_22);
result = scheme_nil;

// Display
SchemeObject* temp_23;
// Quote
result = make_symbol("+");
temp_23 = result;
scheme_display(temp_23);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_24;
result = make_string("Empty list: ");
temp_24 = result;
scheme_display(temp_24);
result = scheme_nil;

// Display
SchemeObject* temp_25;
// Quote
result = scheme_nil;
temp_25 = result;
scheme_display(temp_25);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_26;
result = make_string("2. Testing Arithmetic Operations");
temp_26 = result;
scheme_display(temp_26);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_27;
result = make_string("Addition: ");
temp_27 = result;
scheme_display(temp_27);
result = scheme_nil;

// Display
SchemeObject* temp_28;
// Arithmetic operation
SchemeObject* temp_29;
result = make_number(1);
temp_29 = result;
SchemeObject* temp_30;
result = make_number(2);
temp_30 = result;
temp_29 = scheme_add(temp_29, temp_30);
result = temp_29;
temp_28 = result;
scheme_display(temp_28);
result = scheme_nil;

// Display
SchemeObject* temp_31;
result = make_string(" ");
temp_31 = result;
scheme_display(temp_31);
result = scheme_nil;

// Display
SchemeObject* temp_32;
// Arithmetic operation
SchemeObject* temp_33;
result = make_number(1);
temp_33 = result;
SchemeObject* temp_34;
result = make_number(2);
temp_34 = result;
temp_33 = scheme_add(temp_33, temp_34);
SchemeObject* temp_35;
result = make_number(3);
temp_35 = result;
temp_33 = scheme_add(temp_33, temp_35);
SchemeObject* temp_36;
result = make_number(4);
temp_36 = result;
temp_33 = scheme_add(temp_33, temp_36);
result = temp_33;
temp_32 = result;
scheme_display(temp_32);
result = scheme_nil;

// Display
SchemeObject* temp_37;
result = make_string(" ");
temp_37 = result;
scheme_display(temp_37);
result = scheme_nil;

// Display
SchemeObject* temp_38;
// Arithmetic operation
result = make_number(0);
temp_38 = result;
scheme_display(temp_38);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_39;
result = make_string("Subtraction: ");
temp_39 = result;
scheme_display(temp_39);
result = scheme_nil;

// Display
SchemeObject* temp_40;
// Arithmetic operation
SchemeObject* temp_41;
result = make_number(5);
temp_41 = result;
SchemeObject* temp_42;
result = make_number(3);
temp_42 = result;
temp_41 = scheme_subtract(temp_41, temp_42);
result = temp_41;
temp_40 = result;
scheme_display(temp_40);
result = scheme_nil;

// Display
SchemeObject* temp_43;
result = make_string(" ");
temp_43 = result;
scheme_display(temp_43);
result = scheme_nil;

// Display
SchemeObject* temp_44;
// Arithmetic operation
SchemeObject* temp_45;
result = make_number(10);
temp_45 = result;
SchemeObject* temp_46;
result = make_number(1);
temp_46 = result;
temp_45 = scheme_subtract(temp_45, temp_46);
SchemeObject* temp_47;
result = make_number(2);
temp_47 = result;
temp_45 = scheme_subtract(temp_45, temp_47);
result = temp_45;
temp_44 = result;
scheme_display(temp_44);
result = scheme_nil;

// Display
SchemeObject* temp_48;
result = make_string(" ");
temp_48 = result;
scheme_display(temp_48);
result = scheme_nil;

// Display
SchemeObject* temp_49;
// Arithmetic operation
SchemeObject* temp_50;
result = make_number(0);
temp_50 = result;
SchemeObject* temp_51;
result = make_number(5);
temp_51 = result;
temp_50 = scheme_subtract(temp_50, temp_51);
result = temp_50;
temp_49 = result;
scheme_display(temp_49);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_52;
result = make_string("Multiplication: ");
temp_52 = result;
scheme_display(temp_52);
result = scheme_nil;

// Display
SchemeObject* temp_53;
// Arithmetic operation
SchemeObject* temp_54;
result = make_number(2);
temp_54 = result;
SchemeObject* temp_55;
result = make_number(3);
temp_55 = result;
temp_54 = scheme_multiply(temp_54, temp_55);
result = temp_54;
temp_53 = result;
scheme_display(temp_53);
result = scheme_nil;

// Display
SchemeObject* temp_56;
result = make_string(" ");
temp_56 = result;
scheme_display(temp_56);
result = scheme_nil;

// Display
SchemeObject* temp_57;
// Arithmetic operation
SchemeObject* temp_58;
result = make_number(2);
temp_58 = result;
SchemeObject* temp_59;
result = make_number(3);
temp_59 = result;
temp_58 = scheme_multiply(temp_58, temp_59);
SchemeObject* temp_60;
result = make_number(4);
temp_60 = result;
temp_58 = scheme_multiply(temp_58, temp_60);
result = temp_58;
temp_57 = result;
scheme_display(temp_57);
result = scheme_nil;

// Display
SchemeObject* temp_61;
result = make_string(" ");
temp_61 = result;
scheme_display(temp_61);
result = scheme_nil;

// Display
SchemeObject* temp_62;
// Arithmetic operation
result = make_number(1);
temp_62 = result;
scheme_display(temp_62);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_63;
result = make_string("Division: ");
temp_63 = result;
scheme_display(temp_63);
result = scheme_nil;

// Display
SchemeObject* temp_64;
// Arithmetic operation
SchemeObject* temp_65;
result = make_number(10);
temp_65 = result;
SchemeObject* temp_66;
result = make_number(2);
temp_66 = result;
temp_65 = scheme_divide(temp_65, temp_66);
result = temp_65;
temp_64 = result;
scheme_display(temp_64);
result = scheme_nil;

// Display
SchemeObject* temp_67;
result = make_string(" ");
temp_67 = result;
scheme_display(temp_67);
result = scheme_nil;

// Display
SchemeObject* temp_68;
// Arithmetic operation
SchemeObject* temp_69;
result = make_number(8);
temp_69 = result;
SchemeObject* temp_70;
result = make_number(2);
temp_70 = result;
temp_69 = scheme_divide(temp_69, temp_70);
SchemeObject* temp_71;
result = make_number(2);
temp_71 = result;
temp_69 = scheme_divide(temp_69, temp_71);
result = temp_69;
temp_68 = result;
scheme_display(temp_68);
result = scheme_nil;

// Display
SchemeObject* temp_72;
result = make_string(" ");
temp_72 = result;
scheme_display(temp_72);
result = scheme_nil;

// Display
SchemeObject* temp_73;
// Arithmetic operation
SchemeObject* temp_74;
result = make_number(1);
temp_74 = result;
SchemeObject* temp_75;
result = make_number(5);
temp_75 = result;
temp_74 = scheme_divide(temp_74, temp_75);
result = temp_74;
temp_73 = result;
scheme_display(temp_73);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_76;
result = make_string("3. Testing Comparison Operations");
temp_76 = result;
scheme_display(temp_76);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_77;
result = make_string("Equality: ");
temp_77 = result;
scheme_display(temp_77);
result = scheme_nil;

// Display
SchemeObject* temp_78;
// Comparison operation
SchemeObject* temp_79;
result = make_number(5);
temp_79 = result;
SchemeObject* temp_80;
result = make_number(5);
temp_80 = result;
if (!is_true(scheme_equal(temp_79, temp_80))) {
    result = make_boolean(false);
    goto label_0;
}
temp_79 = temp_80;
result = make_boolean(true);
label_0:;
temp_78 = result;
scheme_display(temp_78);
result = scheme_nil;

// Display
SchemeObject* temp_81;
result = make_string(" ");
temp_81 = result;
scheme_display(temp_81);
result = scheme_nil;

// Display
SchemeObject* temp_82;
// Comparison operation
SchemeObject* temp_83;
result = make_number(3);
temp_83 = result;
SchemeObject* temp_84;
result = make_number(4);
temp_84 = result;
if (!is_true(scheme_equal(temp_83, temp_84))) {
    result = make_boolean(false);
    goto label_1;
}
temp_83 = temp_84;
result = make_boolean(true);
label_1:;
temp_82 = result;
scheme_display(temp_82);
result = scheme_nil;

// Display
SchemeObject* temp_85;
result = make_string(" ");
temp_85 = result;
scheme_display(temp_85);
result = scheme_nil;

// Display
SchemeObject* temp_86;
// Comparison operation
SchemeObject* temp_87;
result = make_number(1);
temp_87 = result;
SchemeObject* temp_88;
result = make_number(1);
temp_88 = result;
if (!is_true(scheme_equal(temp_87, temp_88))) {
    result = make_boolean(false);
    goto label_2;
}
temp_87 = temp_88;
SchemeObject* temp_89;
result = make_number(1);
temp_89 = result;
if (!is_true(scheme_equal(temp_87, temp_89))) {
    result = make_boolean(false);
    goto label_2;
}
temp_87 = temp_89;
result = make_boolean(true);
label_2:;
temp_86 = result;
scheme_display(temp_86);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_90;
result = make_string("Less than: ");
temp_90 = result;
scheme_display(temp_90);
result = scheme_nil;

// Display
SchemeObject* temp_91;
// Comparison operation
SchemeObject* temp_92;
result = make_number(3);
temp_92 = result;
SchemeObject* temp_93;
result = make_number(5);
temp_93 = result;
if (!is_true(scheme_less(temp_92, temp_93))) {
    result = make_boolean(false);
    goto label_3;
}
temp_92 = temp_93;
result = make_boolean(true);
label_3:;
temp_91 = result;
scheme_display(temp_91);
result = scheme_nil;

// Display
SchemeObject* temp_94;
result = make_string(" ");
temp_94 = result;
scheme_display(temp_94);
result = scheme_nil;

// Display
SchemeObject* temp_95;
// Comparison operation
SchemeObject* temp_96;
result = make_number(5);
temp_96 = result;
SchemeObject* temp_97;
result = make_number(3);
temp_97 = result;
if (!is_true(scheme_less(temp_96, temp_97))) {
    result = make_boolean(false);
    goto label_4;
}
temp_96 = temp_97;
result = make_boolean(true);
label_4:;
temp_95 = result;
scheme_display(temp_95);
result = scheme_nil;

// Display
SchemeObject* temp_98;
result = make_string(" ");
temp_98 = result;
scheme_display(temp_98);
result = scheme_nil;

// Display
SchemeObject* temp_99;
// Comparison operation
SchemeObject* temp_100;
result = make_number(1);
temp_100 = result;
SchemeObject* temp_101;
result = make_number(2);
temp_101 = result;
if (!is_true(scheme_less(temp_100, temp_101))) {
    result = make_boolean(false);
    goto label_5;
}
temp_100 = temp_101;
SchemeObject* temp_102;
result = make_number(3);
temp_102 = result;
if (!is_true(scheme_less(temp_100, temp_102))) {
    result = make_boolean(false);
    goto label_5;
}
temp_100 = temp_102;
result = make_boolean(true);
label_5:;
temp_99 = result;
scheme_display(temp_99);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_103;
result = make_string("Greater than: ");
temp_103 = result;
scheme_display(temp_103);
result = scheme_nil;

// Display
SchemeObject* temp_104;
// Comparison operation
SchemeObject* temp_105;
result = make_number(5);
temp_105 = result;
SchemeObject* temp_106;
result = make_number(3);
temp_106 = result;
if (!is_true(scheme_greater(temp_105, temp_106))) {
    result = make_boolean(false);
    goto label_6;
}
temp_105 = temp_106;
result = make_boolean(true);
label_6:;
temp_104 = result;
scheme_display(temp_104);
result = scheme_nil;

// Display
SchemeObject* temp_107;
result = make_string(" ");
temp_107 = result;
scheme_display(temp_107);
result = scheme_nil;

// Display
SchemeObject* temp_108;
// Comparison operation
SchemeObject* temp_109;
result = make_number(3);
temp_109 = result;
SchemeObject* temp_110;
result = make_number(5);
temp_110 = result;
if (!is_true(scheme_greater(temp_109, temp_110))) {
    result = make_boolean(false);
    goto label_7;
}
temp_109 = temp_110;
result = make_boolean(true);
label_7:;
temp_108 = result;
scheme_display(temp_108);
result = scheme_nil;

// Display
SchemeObject* temp_111;
result = make_string(" ");
temp_111 = result;
scheme_display(temp_111);
result = scheme_nil;

// Display
SchemeObject* temp_112;
// Comparison operation
SchemeObject* temp_113;
result = make_number(3);
temp_113 = result;
SchemeObject* temp_114;
result = make_number(2);
temp_114 = result;
if (!is_true(scheme_greater(temp_113, temp_114))) {
    result = make_boolean(false);
    goto label_8;
}
temp_113 = temp_114;
SchemeObject* temp_115;
result = make_number(1);
temp_115 = result;
if (!is_true(scheme_greater(temp_113, temp_115))) {
    result = make_boolean(false);
    goto label_8;
}
temp_113 = temp_115;
result = make_boolean(true);
label_8:;
temp_112 = result;
scheme_display(temp_112);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_116;
result = make_string("Less or equal: ");
temp_116 = result;
scheme_display(temp_116);
result = scheme_nil;

// Display
SchemeObject* temp_117;
// Comparison operation
SchemeObject* temp_118;
result = make_number(3);
temp_118 = result;
SchemeObject* temp_119;
result = make_number(5);
temp_119 = result;
if (!is_true(scheme_less_equal(temp_118, temp_119))) {
    result = make_boolean(false);
    goto label_9;
}
temp_118 = temp_119;
result = make_boolean(true);
label_9:;
temp_117 = result;
scheme_display(temp_117);
result = scheme_nil;

// Display
SchemeObject* temp_120;
result = make_string(" ");
temp_120 = result;
scheme_display(temp_120);
result = scheme_nil;

// Display
SchemeObject* temp_121;
// Comparison operation
SchemeObject* temp_122;
result = make_number(5);
temp_122 = result;
SchemeObject* temp_123;
result = make_number(5);
temp_123 = result;
if (!is_true(scheme_less_equal(temp_122, temp_123))) {
    result = make_boolean(false);
    goto label_10;
}
temp_122 = temp_123;
result = make_boolean(true);
label_10:;
temp_121 = result;
scheme_display(temp_121);
result = scheme_nil;

// Display
SchemeObject* temp_124;
result = make_string(" ");
temp_124 = result;
scheme_display(temp_124);
result = scheme_nil;

// Display
SchemeObject* temp_125;
// Comparison operation
SchemeObject* temp_126;
result = make_number(5);
temp_126 = result;
SchemeObject* temp_127;
result = make_number(3);
temp_127 = result;
if (!is_true(scheme_less_equal(temp_126, temp_127))) {
    result = make_boolean(false);
    goto label_11;
}
temp_126 = temp_127;
result = make_boolean(true);
label_11:;
temp_125 = result;
scheme_display(temp_125);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_128;
result = make_string("Greater or equal: ");
temp_128 = result;
scheme_display(temp_128);
result = scheme_nil;

// Display
SchemeObject* temp_129;
// Comparison operation
SchemeObject* temp_130;
result = make_number(5);
temp_130 = result;
SchemeObject* temp_131;
result = make_number(3);
temp_131 = result;
if (!is_true(scheme_greater_equal(temp_130, temp_131))) {
    result = make_boolean(false);
    goto label_12;
}
temp_130 = temp_131;
result = make_boolean(true);
label_12:;
temp_129 = result;
scheme_display(temp_129);
result = scheme_nil;

// Display
SchemeObject* temp_132;
result = make_string(" ");
temp_132 = result;
scheme_display(temp_132);
result = scheme_nil;

// Display
SchemeObject* temp_133;
// Comparison operation
SchemeObject* temp_134;
result = make_number(5);
temp_134 = result;
SchemeObject* temp_135;
result = make_number(5);
temp_135 = result;
if (!is_true(scheme_greater_equal(temp_134, temp_135))) {
    result = make_boolean(false);
    goto label_13;
}
temp_134 = temp_135;
result = make_boolean(true);
label_13:;
temp_133 = result;
scheme_display(temp_133);
result = scheme_nil;

// Display
SchemeObject* temp_136;
result = make_string(" ");
temp_136 = result;
scheme_display(temp_136);
result = scheme_nil;

// Display
SchemeObject* temp_137;
// Comparison operation
SchemeObject* temp_138;
result = make_number(3);
temp_138 = result;
SchemeObject* temp_139;
result = make_number(5);
temp_139 = result;
if (!is_true(scheme_greater_equal(temp_138, temp_139))) {
    result = make_boolean(false);
    goto label_14;
}
temp_138 = temp_139;
result = make_boolean(true);
label_14:;
temp_137 = result;
scheme_display(temp_137);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_140;
result = make_string("4. Testing Variable Definition");
temp_140 = result;
scheme_display(temp_140);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
result = make_number(42);
define_variable("x", result);
// Variable 'x' defined

// Display
SchemeObject* temp_141;
result = make_string("Defined x = 42: ");
temp_141 = result;
scheme_display(temp_141);
result = scheme_nil;

// Display
SchemeObject* temp_142;
result = lookup_variable("x");
temp_142 = result;
scheme_display(temp_142);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Arithmetic operation
SchemeObject* temp_143;
result = lookup_variable("x");
temp_143 = result;
SchemeObject* temp_144;
result = make_number(8);
temp_144 = result;
temp_143 = scheme_add(temp_143, temp_144);
result = temp_143;
define_variable("y", result);
// Variable 'y' defined

// Display
SchemeObject* temp_145;
result = make_string("Defined y = (+ x 8): ");
temp_145 = result;
scheme_display(temp_145);
result = scheme_nil;

// Display
SchemeObject* temp_146;
result = lookup_variable("y");
temp_146 = result;
scheme_display(temp_146);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
result = make_string("R5RS Scheme");
define_variable("name", result);
// Variable 'name' defined

// Display
SchemeObject* temp_147;
result = make_string("Defined name = ");
temp_147 = result;
scheme_display(temp_147);
result = scheme_nil;

// Display
SchemeObject* temp_148;
result = lookup_variable("name");
temp_148 = result;
scheme_display(temp_148);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_149;
result = make_string("5. Testing Conditional Expressions");
temp_149 = result;
scheme_display(temp_149);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_150;
result = make_string("If true: ");
temp_150 = result;
scheme_display(temp_150);
result = scheme_nil;

// Display
SchemeObject* temp_151;
// if expression
SchemeObject* temp_152;
result = make_boolean(true);
temp_152 = result;
if (!is_true(temp_152)) goto label_15;
result = make_string("yes");
goto label_16;
label_15:
result = make_string("no");
label_16:
temp_151 = result;
scheme_display(temp_151);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_153;
result = make_string("If false: ");
temp_153 = result;
scheme_display(temp_153);
result = scheme_nil;

// Display
SchemeObject* temp_154;
// if expression
SchemeObject* temp_155;
result = make_boolean(false);
temp_155 = result;
if (!is_true(temp_155)) goto label_17;
result = make_string("yes");
goto label_18;
label_17:
result = make_string("no");
label_18:
temp_154 = result;
scheme_display(temp_154);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_156;
result = make_string("If with expression: ");
temp_156 = result;
scheme_display(temp_156);
result = scheme_nil;

// Display
SchemeObject* temp_157;
// if expression
SchemeObject* temp_158;
// Comparison operation
SchemeObject* temp_159;
result = make_number(5);
temp_159 = result;
SchemeObject* temp_160;
result = make_number(3);
temp_160 = result;
if (!is_true(scheme_greater(temp_159, temp_160))) {
    result = make_boolean(false);
    goto label_21;
}
temp_159 = temp_160;
result = make_boolean(true);
label_21:;
temp_158 = result;
if (!is_true(temp_158)) goto label_19;
result = make_string("greater");
goto label_20;
label_19:
result = make_string("not greater");
label_20:
temp_157 = result;
scheme_display(temp_157);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_161;
result = make_string("If without else: ");
temp_161 = result;
scheme_display(temp_161);
result = scheme_nil;

// Display
SchemeObject* temp_162;
// if expression
SchemeObject* temp_163;
result = make_boolean(true);
temp_163 = result;
if (!is_true(temp_163)) goto label_22;
result = make_string("present");
goto label_23;
label_22:
result = scheme_nil;
label_23:
temp_162 = result;
scheme_display(temp_162);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_164;
result = make_string("6. Testing Lists and Pairs");
temp_164 = result;
scheme_display(temp_164);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_165;
result = make_string("Empty list: ");
temp_165 = result;
scheme_display(temp_165);
result = scheme_nil;

// Display
SchemeObject* temp_166;
// Quote
result = scheme_nil;
temp_166 = result;
scheme_display(temp_166);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Quote
// Building simple quoted list
{
    SchemeObject* elements[4];
    elements[0] = make_number(1);
    elements[1] = make_number(2);
    elements[2] = make_number(3);
    elements[3] = make_number(4);
    result = scheme_nil;
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
define_variable("simple-list", result);
// Variable 'simple-list' defined

// Display
SchemeObject* temp_167;
result = make_string("Simple list: ");
temp_167 = result;
scheme_display(temp_167);
result = scheme_nil;

// Display
SchemeObject* temp_168;
result = lookup_variable("simple-list");
temp_168 = result;
scheme_display(temp_168);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Quote
// Building simple quoted list
{
    SchemeObject* elements[4];
    elements[0] = make_number(1);
    elements[1] = make_string("hello");
    elements[2] = make_boolean(true);
    elements[3] = make_symbol("x");
    result = scheme_nil;
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
define_variable("mixed-list", result);
// Variable 'mixed-list' defined

// Display
SchemeObject* temp_169;
result = make_string("Mixed list: ");
temp_169 = result;
scheme_display(temp_169);
result = scheme_nil;

// Display
SchemeObject* temp_170;
result = lookup_variable("mixed-list");
temp_170 = result;
scheme_display(temp_170);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Quote
{
    SchemeObject* car_part;
    SchemeObject* cdr_part;
    // Compile car of pair
    {
        SchemeObject* temp_result_171;
        car_part = scheme_nil; // Complex quoted value
    }
    // Compile cdr of pair
    {
        cdr_part = scheme_nil; // Complex quoted value
    }
    result = make_pair(car_part, cdr_part);
}
define_variable("nested-list", result);
// Variable 'nested-list' defined

// Display
SchemeObject* temp_173;
result = make_string("Nested list: ");
temp_173 = result;
scheme_display(temp_173);
result = scheme_nil;

// Display
SchemeObject* temp_174;
result = lookup_variable("nested-list");
temp_174 = result;
scheme_display(temp_174);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Cons operation
SchemeObject* temp_175;
SchemeObject* temp_176;
// Quote
result = make_symbol("a");
temp_175 = result;
// Quote
result = make_symbol("b");
temp_176 = result;
result = make_pair(temp_175, temp_176);
define_variable("my-pair", result);
// Variable 'my-pair' defined

// Display
SchemeObject* temp_177;
result = make_string("Pair: ");
temp_177 = result;
scheme_display(temp_177);
result = scheme_nil;

// Display
SchemeObject* temp_178;
result = lookup_variable("my-pair");
temp_178 = result;
scheme_display(temp_178);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_179;
result = make_string("7. Testing List Operations");
temp_179 = result;
scheme_display(temp_179);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_180;
result = make_string("car of (1 2 3 4): ");
temp_180 = result;
scheme_display(temp_180);
result = scheme_nil;

// Display
SchemeObject* temp_181;
// car
SchemeObject* temp_182;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[4];
    elements[0] = make_number(1);
    elements[1] = make_number(2);
    elements[2] = make_number(3);
    elements[3] = make_number(4);
    result = scheme_nil;
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_182 = result;
result = scheme_car(temp_182);
temp_181 = result;
scheme_display(temp_181);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_183;
result = make_string("cdr of (1 2 3 4): ");
temp_183 = result;
scheme_display(temp_183);
result = scheme_nil;

// Display
SchemeObject* temp_184;
// cdr
SchemeObject* temp_185;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[4];
    elements[0] = make_number(1);
    elements[1] = make_number(2);
    elements[2] = make_number(3);
    elements[3] = make_number(4);
    result = scheme_nil;
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_185 = result;
result = scheme_cdr(temp_185);
temp_184 = result;
scheme_display(temp_184);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_186;
result = make_string("cons 0 to (1 2 3 4): ");
temp_186 = result;
scheme_display(temp_186);
result = scheme_nil;

// Display
SchemeObject* temp_187;
// Cons operation
SchemeObject* temp_188;
SchemeObject* temp_189;
result = make_number(0);
temp_188 = result;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[4];
    elements[0] = make_number(1);
    elements[1] = make_number(2);
    elements[2] = make_number(3);
    elements[3] = make_number(4);
    result = scheme_nil;
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_189 = result;
result = make_pair(temp_188, temp_189);
temp_187 = result;
scheme_display(temp_187);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_190;
result = make_string("8. Testing Lambda and Procedures");
temp_190 = result;
scheme_display(temp_190);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Lambda expression
// Compiling lambda - collecting function
// Compiling lambda - collecting function
// Lambda args structure debugging
// Extracted body operator: *
// Lambda function collected successfully
result = make_compiled_procedure(lambda_func_0, 1, "lambda_func_0");
define_variable("square", result);
// Variable 'square' defined

// Display
SchemeObject* temp_191;
result = make_string("Square of 5: ");
temp_191 = result;
scheme_display(temp_191);
result = scheme_nil;

// Display
SchemeObject* temp_192;
// Procedure call
SchemeObject* temp_193;
result = lookup_variable("square");
temp_193 = result;
if (temp_193 && temp_193->type == SCHEME_PROCEDURE) {
    SchemeObject* proc_args[1];
    SchemeObject* temp_194;
result = make_number(5);
    temp_194 = result;
    proc_args[0] = temp_194;
    result = temp_193->value.procedure.func(proc_args, 1);
} else {
    result = scheme_nil; // Not a procedure
}
temp_192 = result;
scheme_display(temp_192);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Lambda expression
// Compiling lambda - collecting function
// Compiling lambda - collecting function
// Lambda args structure debugging
// Extracted body operator: +
// Lambda function collected successfully
result = make_compiled_procedure(lambda_func_1, 2, "lambda_func_1");
define_variable("add", result);
// Variable 'add' defined

// Display
SchemeObject* temp_195;
result = make_string("Add 3 and 4: ");
temp_195 = result;
scheme_display(temp_195);
result = scheme_nil;

// Display
SchemeObject* temp_196;
// Procedure call
SchemeObject* temp_197;
result = lookup_variable("add");
temp_197 = result;
if (temp_197 && temp_197->type == SCHEME_PROCEDURE) {
    SchemeObject* proc_args[2];
    SchemeObject* temp_198;
result = make_number(3);
    temp_198 = result;
    proc_args[0] = temp_198;
    SchemeObject* temp_199;
result = make_number(4);
    temp_199 = result;
    proc_args[1] = temp_199;
    result = temp_197->value.procedure.func(proc_args, 2);
} else {
    result = scheme_nil; // Not a procedure
}
temp_196 = result;
scheme_display(temp_196);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Lambda expression
// Compiling lambda - collecting function
// Compiling lambda - collecting function
// Lambda args structure debugging
// Lambda function collected successfully
result = make_compiled_procedure(lambda_func_2, 0, "lambda_func_2");
define_variable("pi", result);
// Variable 'pi' defined

// Display
SchemeObject* temp_200;
result = make_string("Pi: ");
temp_200 = result;
scheme_display(temp_200);
result = scheme_nil;

// Display
SchemeObject* temp_201;
// Procedure call
SchemeObject* temp_202;
result = lookup_variable("pi");
temp_202 = result;
if (temp_202 && temp_202->type == SCHEME_PROCEDURE) {
    result = temp_202->value.procedure.func(NULL, 0);
} else {
    result = scheme_nil; // Not a procedure
}
temp_201 = result;
scheme_display(temp_201);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Lambda expression
// Compiling lambda - collecting function
// Compiling lambda - collecting function
// Lambda args structure debugging
// Extracted body operator: if
// Lambda function collected successfully
result = make_compiled_procedure(lambda_func_3, 1, "lambda_func_3");
define_variable("factorial", result);
// Variable 'factorial' defined

// Display
SchemeObject* temp_203;
result = make_string("Factorial of 5: ");
temp_203 = result;
scheme_display(temp_203);
result = scheme_nil;

// Display
SchemeObject* temp_204;
// Procedure call
SchemeObject* temp_205;
result = lookup_variable("factorial");
temp_205 = result;
if (temp_205 && temp_205->type == SCHEME_PROCEDURE) {
    SchemeObject* proc_args[1];
    SchemeObject* temp_206;
result = make_number(5);
    temp_206 = result;
    proc_args[0] = temp_206;
    result = temp_205->value.procedure.func(proc_args, 1);
} else {
    result = scheme_nil; // Not a procedure
}
temp_204 = result;
scheme_display(temp_204);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_207;
result = make_string("9. Testing Advanced Control");
temp_207 = result;
scheme_display(temp_207);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_208;
result = make_string("Begin result: ");
temp_208 = result;
scheme_display(temp_208);
result = scheme_nil;

// Display
SchemeObject* temp_209;
// Begin sequence
// Define variable
result = make_number(10);
define_variable("temp", result);
// Variable 'temp' defined
// Discard intermediate result
// Arithmetic operation
SchemeObject* temp_210;
result = lookup_variable("temp");
temp_210 = result;
SchemeObject* temp_211;
result = make_number(5);
temp_211 = result;
temp_210 = scheme_add(temp_210, temp_211);
result = temp_210;
temp_209 = result;
scheme_display(temp_209);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
result = make_number(100);
define_variable("counter", result);
// Variable 'counter' defined

// Display
SchemeObject* temp_212;
result = make_string("Before set!: ");
temp_212 = result;
scheme_display(temp_212);
result = scheme_nil;

// Display
SchemeObject* temp_213;
result = lookup_variable("counter");
temp_213 = result;
scheme_display(temp_213);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Set! - Variable assignment
result = make_number(200);
define_variable("counter", result);
// Variable 'counter' updated via set!

// Display
SchemeObject* temp_214;
result = make_string("After set!: ");
temp_214 = result;
scheme_display(temp_214);
result = scheme_nil;

// Display
SchemeObject* temp_215;
result = lookup_variable("counter");
temp_215 = result;
scheme_display(temp_215);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_216;
result = make_string("10. Testing Type Predicates");
temp_216 = result;
scheme_display(temp_216);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_217;
result = make_string("number? tests: ");
temp_217 = result;
scheme_display(temp_217);
result = scheme_nil;

// Display
SchemeObject* temp_218;
// number_p
SchemeObject* temp_219;
result = make_number(42);
temp_219 = result;
result = scheme_number_p(temp_219);
temp_218 = result;
scheme_display(temp_218);
result = scheme_nil;

// Display
SchemeObject* temp_220;
result = make_string(" ");
temp_220 = result;
scheme_display(temp_220);
result = scheme_nil;

// Display
SchemeObject* temp_221;
// number_p
SchemeObject* temp_222;
result = make_string("hello");
temp_222 = result;
result = scheme_number_p(temp_222);
temp_221 = result;
scheme_display(temp_221);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_223;
result = make_string("boolean? tests: ");
temp_223 = result;
scheme_display(temp_223);
result = scheme_nil;

// Display
SchemeObject* temp_224;
// boolean_p
SchemeObject* temp_225;
result = make_boolean(true);
temp_225 = result;
result = scheme_boolean_p(temp_225);
temp_224 = result;
scheme_display(temp_224);
result = scheme_nil;

// Display
SchemeObject* temp_226;
result = make_string(" ");
temp_226 = result;
scheme_display(temp_226);
result = scheme_nil;

// Display
SchemeObject* temp_227;
// boolean_p
SchemeObject* temp_228;
result = make_number(42);
temp_228 = result;
result = scheme_boolean_p(temp_228);
temp_227 = result;
scheme_display(temp_227);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_229;
result = make_string("string? tests: ");
temp_229 = result;
scheme_display(temp_229);
result = scheme_nil;

// Display
SchemeObject* temp_230;
// string_p
SchemeObject* temp_231;
result = make_string("hello");
temp_231 = result;
result = scheme_string_p(temp_231);
temp_230 = result;
scheme_display(temp_230);
result = scheme_nil;

// Display
SchemeObject* temp_232;
result = make_string(" ");
temp_232 = result;
scheme_display(temp_232);
result = scheme_nil;

// Display
SchemeObject* temp_233;
// string_p
SchemeObject* temp_234;
result = make_number(42);
temp_234 = result;
result = scheme_string_p(temp_234);
temp_233 = result;
scheme_display(temp_233);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_235;
result = make_string("symbol? tests: ");
temp_235 = result;
scheme_display(temp_235);
result = scheme_nil;

// Display
SchemeObject* temp_236;
// symbol_p
SchemeObject* temp_237;
// Quote
result = make_symbol("hello");
temp_237 = result;
result = scheme_symbol_p(temp_237);
temp_236 = result;
scheme_display(temp_236);
result = scheme_nil;

// Display
SchemeObject* temp_238;
result = make_string(" ");
temp_238 = result;
scheme_display(temp_238);
result = scheme_nil;

// Display
SchemeObject* temp_239;
// symbol_p
SchemeObject* temp_240;
result = make_string("hello");
temp_240 = result;
result = scheme_symbol_p(temp_240);
temp_239 = result;
scheme_display(temp_239);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_241;
result = make_string("pair? tests: ");
temp_241 = result;
scheme_display(temp_241);
result = scheme_nil;

// Display
SchemeObject* temp_242;
// pair_p
SchemeObject* temp_243;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[1];
    elements[0] = make_number(1);
    result = scheme_nil;
    result = make_pair(elements[0], result);
}
temp_243 = result;
result = scheme_pair_p(temp_243);
temp_242 = result;
scheme_display(temp_242);
result = scheme_nil;

// Display
SchemeObject* temp_244;
result = make_string(" ");
temp_244 = result;
scheme_display(temp_244);
result = scheme_nil;

// Display
SchemeObject* temp_245;
// pair_p
SchemeObject* temp_246;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[2];
    elements[0] = make_number(1);
    elements[1] = make_number(2);
    result = scheme_nil;
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_246 = result;
result = scheme_pair_p(temp_246);
temp_245 = result;
scheme_display(temp_245);
result = scheme_nil;

// Display
SchemeObject* temp_247;
result = make_string(" ");
temp_247 = result;
scheme_display(temp_247);
result = scheme_nil;

// Display
SchemeObject* temp_248;
// pair_p
SchemeObject* temp_249;
result = make_number(42);
temp_249 = result;
result = scheme_pair_p(temp_249);
temp_248 = result;
scheme_display(temp_248);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_250;
result = make_string("null? tests: ");
temp_250 = result;
scheme_display(temp_250);
result = scheme_nil;

// Display
SchemeObject* temp_251;
// null_p
SchemeObject* temp_252;
// Quote
result = scheme_nil;
temp_252 = result;
result = scheme_null_p(temp_252);
temp_251 = result;
scheme_display(temp_251);
result = scheme_nil;

// Display
SchemeObject* temp_253;
result = make_string(" ");
temp_253 = result;
scheme_display(temp_253);
result = scheme_nil;

// Display
SchemeObject* temp_254;
// null_p
SchemeObject* temp_255;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[2];
    elements[0] = make_number(1);
    elements[1] = make_number(2);
    result = scheme_nil;
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_255 = result;
result = scheme_null_p(temp_255);
temp_254 = result;
scheme_display(temp_254);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_256;
result = make_string("procedure? tests: ");
temp_256 = result;
scheme_display(temp_256);
result = scheme_nil;

// Display
SchemeObject* temp_257;
// procedure_p
SchemeObject* temp_258;
result = lookup_variable("+");
temp_258 = result;
result = scheme_procedure_p(temp_258);
temp_257 = result;
scheme_display(temp_257);
result = scheme_nil;

// Display
SchemeObject* temp_259;
result = make_string(" ");
temp_259 = result;
scheme_display(temp_259);
result = scheme_nil;

// Display
SchemeObject* temp_260;
// procedure_p
SchemeObject* temp_261;
result = lookup_variable("square");
temp_261 = result;
result = scheme_procedure_p(temp_261);
temp_260 = result;
scheme_display(temp_260);
result = scheme_nil;

// Display
SchemeObject* temp_262;
result = make_string(" ");
temp_262 = result;
scheme_display(temp_262);
result = scheme_nil;

// Display
SchemeObject* temp_263;
// procedure_p
SchemeObject* temp_264;
result = make_number(42);
temp_264 = result;
result = scheme_procedure_p(temp_264);
temp_263 = result;
scheme_display(temp_263);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_265;
result = make_string("11. Testing Additional List Functions");
temp_265 = result;
scheme_display(temp_265);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_266;
result = make_string("length of (a b c d e): ");
temp_266 = result;
scheme_display(temp_266);
result = scheme_nil;

// Display
SchemeObject* temp_267;
// length
SchemeObject* temp_268;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[5];
    elements[0] = make_symbol("a");
    elements[1] = make_symbol("b");
    elements[2] = make_symbol("c");
    elements[3] = make_symbol("d");
    elements[4] = make_symbol("e");
    result = scheme_nil;
    result = make_pair(elements[4], result);
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_268 = result;
result = scheme_length(temp_268);
temp_267 = result;
scheme_display(temp_267);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_269;
result = make_string("list-ref (a b c d e) 2: ");
temp_269 = result;
scheme_display(temp_269);
result = scheme_nil;

// Display
SchemeObject* temp_270;
// list_ref
SchemeObject* temp_271;
SchemeObject* temp_272;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[5];
    elements[0] = make_symbol("a");
    elements[1] = make_symbol("b");
    elements[2] = make_symbol("c");
    elements[3] = make_symbol("d");
    elements[4] = make_symbol("e");
    result = scheme_nil;
    result = make_pair(elements[4], result);
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_271 = result;
result = make_number(2);
temp_272 = result;
result = scheme_list_ref(temp_271, temp_272);
temp_270 = result;
scheme_display(temp_270);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_273;
result = make_string("append (1 2) (3 4): ");
temp_273 = result;
scheme_display(temp_273);
result = scheme_nil;

// Display
SchemeObject* temp_274;
// Append
SchemeObject* temp_275;
SchemeObject* temp_276;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[2];
    elements[0] = make_number(1);
    elements[1] = make_number(2);
    result = scheme_nil;
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_275 = result;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[2];
    elements[0] = make_number(3);
    elements[1] = make_number(4);
    result = scheme_nil;
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_276 = result;
result = scheme_append(temp_275, temp_276);
temp_274 = result;
scheme_display(temp_274);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_277;
result = make_string("reverse (1 2 3 4): ");
temp_277 = result;
scheme_display(temp_277);
result = scheme_nil;

// Display
SchemeObject* temp_278;
// reverse
SchemeObject* temp_279;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[4];
    elements[0] = make_number(1);
    elements[1] = make_number(2);
    elements[2] = make_number(3);
    elements[3] = make_number(4);
    result = scheme_nil;
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_279 = result;
result = scheme_reverse(temp_279);
temp_278 = result;
scheme_display(temp_278);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_280;
result = make_string("12. Testing String Operations");
temp_280 = result;
scheme_display(temp_280);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_281;
result = make_string("string-length of ");
temp_281 = result;
scheme_display(temp_281);
result = scheme_nil;

// Display
SchemeObject* temp_282;
result = make_string("hello");
temp_282 = result;
scheme_display(temp_282);
result = scheme_nil;

// Display
SchemeObject* temp_283;
result = make_string(": ");
temp_283 = result;
scheme_display(temp_283);
result = scheme_nil;

// Display
SchemeObject* temp_284;
// string_length
SchemeObject* temp_285;
result = make_string("hello");
temp_285 = result;
result = scheme_string_length(temp_285);
temp_284 = result;
scheme_display(temp_284);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_286;
result = make_string("string-ref ");
temp_286 = result;
scheme_display(temp_286);
result = scheme_nil;

// Display
SchemeObject* temp_287;
result = make_string("hello");
temp_287 = result;
scheme_display(temp_287);
result = scheme_nil;

// Display
SchemeObject* temp_288;
result = make_string(" 1: ");
temp_288 = result;
scheme_display(temp_288);
result = scheme_nil;

// Display
SchemeObject* temp_289;
// string_ref
SchemeObject* temp_290;
SchemeObject* temp_291;
result = make_string("hello");
temp_290 = result;
result = make_number(1);
temp_291 = result;
result = scheme_string_ref(temp_290, temp_291);
temp_289 = result;
scheme_display(temp_289);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_292;
result = make_string("13. Testing Complex Expressions");
temp_292 = result;
scheme_display(temp_292);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_293;
result = make_string("Nested arithmetic: ");
temp_293 = result;
scheme_display(temp_293);
result = scheme_nil;

// Display
SchemeObject* temp_294;
// Arithmetic operation
SchemeObject* temp_295;
// Arithmetic operation
SchemeObject* temp_296;
result = make_number(2);
temp_296 = result;
SchemeObject* temp_297;
result = make_number(3);
temp_297 = result;
temp_296 = scheme_multiply(temp_296, temp_297);
result = temp_296;
temp_295 = result;
SchemeObject* temp_298;
// Arithmetic operation
SchemeObject* temp_299;
result = make_number(7);
temp_299 = result;
SchemeObject* temp_300;
result = make_number(2);
temp_300 = result;
temp_299 = scheme_subtract(temp_299, temp_300);
result = temp_299;
temp_298 = result;
temp_295 = scheme_add(temp_295, temp_298);
result = temp_295;
temp_294 = result;
scheme_display(temp_294);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_301;
result = make_string("Nested conditionals: ");
temp_301 = result;
scheme_display(temp_301);
result = scheme_nil;

// Display
SchemeObject* temp_302;
// if expression
SchemeObject* temp_303;
// Procedure call
SchemeObject* temp_304;
result = lookup_variable("and");
temp_304 = result;
if (temp_304 && temp_304->type == SCHEME_PROCEDURE) {
    SchemeObject* proc_args[2];
    SchemeObject* temp_305;
// Comparison operation
SchemeObject* temp_306;
result = make_number(5);
temp_306 = result;
SchemeObject* temp_307;
result = make_number(3);
temp_307 = result;
if (!is_true(scheme_greater(temp_306, temp_307))) {
    result = make_boolean(false);
    goto label_26;
}
temp_306 = temp_307;
result = make_boolean(true);
label_26:;
    temp_305 = result;
    proc_args[0] = temp_305;
    SchemeObject* temp_308;
// Comparison operation
SchemeObject* temp_309;
result = make_number(2);
temp_309 = result;
SchemeObject* temp_310;
result = make_number(4);
temp_310 = result;
if (!is_true(scheme_less(temp_309, temp_310))) {
    result = make_boolean(false);
    goto label_27;
}
temp_309 = temp_310;
result = make_boolean(true);
label_27:;
    temp_308 = result;
    proc_args[1] = temp_308;
    result = temp_304->value.procedure.func(proc_args, 2);
} else {
    result = scheme_nil; // Not a procedure
}
temp_303 = result;
if (!is_true(temp_303)) goto label_24;
result = make_string("both true");
goto label_25;
label_24:
result = make_string("not both true");
label_25:
temp_302 = result;
scheme_display(temp_302);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Define variable
// Lambda expression
// Compiling lambda - collecting function
// Compiling lambda - collecting function
// Lambda args structure debugging
// Extracted body operator: square
// Lambda function collected successfully
result = make_compiled_procedure(lambda_func_4, 1, "lambda_func_4");
define_variable("compose-example", result);
// Variable 'compose-example' defined

// Display
SchemeObject* temp_311;
result = make_string("Compose example: ");
temp_311 = result;
scheme_display(temp_311);
result = scheme_nil;

// Display
SchemeObject* temp_312;
// Procedure call
SchemeObject* temp_313;
result = lookup_variable("compose-example");
temp_313 = result;
if (temp_313 && temp_313->type == SCHEME_PROCEDURE) {
    SchemeObject* proc_args[1];
    SchemeObject* temp_314;
result = make_number(2);
    temp_314 = result;
    proc_args[0] = temp_314;
    result = temp_313->value.procedure.func(proc_args, 1);
} else {
    result = scheme_nil; // Not a procedure
}
temp_312 = result;
scheme_display(temp_312);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_315;
result = make_string("14. Testing Edge Cases");
temp_315 = result;
scheme_display(temp_315);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_316;
result = make_string("Zero tests: ");
temp_316 = result;
scheme_display(temp_316);
result = scheme_nil;

// Display
SchemeObject* temp_317;
// Arithmetic operation
SchemeObject* temp_318;
result = make_number(0);
temp_318 = result;
SchemeObject* temp_319;
result = make_number(0);
temp_319 = result;
temp_318 = scheme_add(temp_318, temp_319);
result = temp_318;
temp_317 = result;
scheme_display(temp_317);
result = scheme_nil;

// Display
SchemeObject* temp_320;
result = make_string(" ");
temp_320 = result;
scheme_display(temp_320);
result = scheme_nil;

// Display
SchemeObject* temp_321;
// Arithmetic operation
SchemeObject* temp_322;
result = make_number(5);
temp_322 = result;
SchemeObject* temp_323;
result = make_number(0);
temp_323 = result;
temp_322 = scheme_multiply(temp_322, temp_323);
result = temp_322;
temp_321 = result;
scheme_display(temp_321);
result = scheme_nil;

// Display
SchemeObject* temp_324;
result = make_string(" ");
temp_324 = result;
scheme_display(temp_324);
result = scheme_nil;

// Display
SchemeObject* temp_325;
// Comparison operation
SchemeObject* temp_326;
result = make_number(0);
temp_326 = result;
SchemeObject* temp_327;
result = make_number(0);
temp_327 = result;
if (!is_true(scheme_equal(temp_326, temp_327))) {
    result = make_boolean(false);
    goto label_28;
}
temp_326 = temp_327;
result = make_boolean(true);
label_28:;
temp_325 = result;
scheme_display(temp_325);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_328;
result = make_string("Empty string length: ");
temp_328 = result;
scheme_display(temp_328);
result = scheme_nil;

// Display
SchemeObject* temp_329;
// string_length
SchemeObject* temp_330;
result = make_string("");
temp_330 = result;
result = scheme_string_length(temp_330);
temp_329 = result;
scheme_display(temp_329);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_331;
result = make_string("Single element list: ");
temp_331 = result;
scheme_display(temp_331);
result = scheme_nil;

// Display
SchemeObject* temp_332;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[1];
    elements[0] = make_symbol("only");
    result = scheme_nil;
    result = make_pair(elements[0], result);
}
temp_332 = result;
scheme_display(temp_332);
result = scheme_nil;

// Display
SchemeObject* temp_333;
result = make_string(" car: ");
temp_333 = result;
scheme_display(temp_333);
result = scheme_nil;

// Display
SchemeObject* temp_334;
// car
SchemeObject* temp_335;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[1];
    elements[0] = make_symbol("only");
    result = scheme_nil;
    result = make_pair(elements[0], result);
}
temp_335 = result;
result = scheme_car(temp_335);
temp_334 = result;
scheme_display(temp_334);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_336;
result = make_string("Deeply nested: ");
temp_336 = result;
scheme_display(temp_336);
result = scheme_nil;

// Display
SchemeObject* temp_337;
// Arithmetic operation
SchemeObject* temp_338;
result = make_number(1);
temp_338 = result;
SchemeObject* temp_339;
// Arithmetic operation
SchemeObject* temp_340;
result = make_number(2);
temp_340 = result;
SchemeObject* temp_341;
// Arithmetic operation
SchemeObject* temp_342;
result = make_number(3);
temp_342 = result;
SchemeObject* temp_343;
// Arithmetic operation
SchemeObject* temp_344;
result = make_number(4);
temp_344 = result;
SchemeObject* temp_345;
result = make_number(5);
temp_345 = result;
temp_344 = scheme_add(temp_344, temp_345);
result = temp_344;
temp_343 = result;
temp_342 = scheme_add(temp_342, temp_343);
result = temp_342;
temp_341 = result;
temp_340 = scheme_add(temp_340, temp_341);
result = temp_340;
temp_339 = result;
temp_338 = scheme_add(temp_338, temp_339);
result = temp_338;
temp_337 = result;
scheme_display(temp_337);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_346;
result = make_string("15. Testing Quoting");
temp_346 = result;
scheme_display(temp_346);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_347;
result = make_string("Quoted list: ");
temp_347 = result;
scheme_display(temp_347);
result = scheme_nil;

// Display
SchemeObject* temp_348;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[4];
    elements[0] = make_symbol("+");
    elements[1] = make_number(1);
    elements[2] = make_number(2);
    elements[3] = make_number(3);
    result = scheme_nil;
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_348 = result;
scheme_display(temp_348);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_349;
result = make_string("Evaluated: ");
temp_349 = result;
scheme_display(temp_349);
result = scheme_nil;

// Display
SchemeObject* temp_350;
// Arithmetic operation
SchemeObject* temp_351;
result = make_number(1);
temp_351 = result;
SchemeObject* temp_352;
result = make_number(2);
temp_352 = result;
temp_351 = scheme_add(temp_351, temp_352);
SchemeObject* temp_353;
result = make_number(3);
temp_353 = result;
temp_351 = scheme_add(temp_351, temp_353);
result = temp_351;
temp_350 = result;
scheme_display(temp_350);
result = scheme_nil;

// Display
SchemeObject* temp_354;
result = make_string(" Quoted: ");
temp_354 = result;
scheme_display(temp_354);
result = scheme_nil;

// Display
SchemeObject* temp_355;
// Quote
// Building simple quoted list
{
    SchemeObject* elements[4];
    elements[0] = make_symbol("+");
    elements[1] = make_number(1);
    elements[2] = make_number(2);
    elements[3] = make_number(3);
    result = scheme_nil;
    result = make_pair(elements[3], result);
    result = make_pair(elements[2], result);
    result = make_pair(elements[1], result);
    result = make_pair(elements[0], result);
}
temp_355 = result;
scheme_display(temp_355);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_356;
result = make_string("Nested quotes: ");
temp_356 = result;
scheme_display(temp_356);
result = scheme_nil;

// Display
SchemeObject* temp_357;
// Quote
{
    SchemeObject* car_part;
    SchemeObject* cdr_part;
    // Compile car of pair
    {
        SchemeObject* temp_result_358;
        car_part = scheme_nil; // Complex quoted value
    }
    // Compile cdr of pair
    {
        cdr_part = scheme_nil; // Complex quoted value
    }
    result = make_pair(car_part, cdr_part);
}
temp_357 = result;
scheme_display(temp_357);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_360;
result = make_string("=== R5RS Compliance Test Complete ===");
temp_360 = result;
scheme_display(temp_360);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_361;
result = make_string("If you see this message, the R5RS Scheme implementation");
temp_361 = result;
scheme_display(temp_361);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_362;
result = make_string("successfully processed all major language features!");
temp_362 = result;
scheme_display(temp_362);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

// Display
SchemeObject* temp_363;
result = make_string("Test completed successfully.");
temp_363 = result;
scheme_display(temp_363);
result = scheme_nil;

// Newline
printf("\n");
result = scheme_nil;

    return 0;
}
